name: Node.js CI

on:
  push:
    branches: [ develop, main ]
  pull_request:

jobs:
  nodejs-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [ 16.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci
        working-directory: server
      - run: npm run build --if-present
        working-directory: server
      - run: npm test -- --coverage
        working-directory: server

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
